import { Game, UserProfile } from "../shared/types";

export const games: Game[] = [
    {
        gameId: 'G001',
        userId: 'user123',
        title: 'Adventure Quest',
        genre: 'RPG',
        releaseYear: 2022,
        description: 'Embark on an epic adventure to save the kingdom from the ancient curse.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 87,
    },
    {
        gameId: 'G002',
        userId: 'user234',
        title: 'Mystery of the Ancients',
        genre: 'Puzzle',
        releaseYear: 2021,
        description: 'Solve ancient puzzles to uncover the secrets of a long-lost civilization.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 75,
    },
    {
        gameId: 'G003',
        userId: 'user345',
        title: 'Space Odyssey',
        genre: 'Sci-Fi',
        releaseYear: 2003,
        description: 'Explore the vast universe and battle alien species to protect humanity.',
        platform: ['PC', 'PlayStation'],
        popularity: 92,
    },
    {
        gameId: 'G004',
        userId: 'user456',
        title: 'Farm Frenzy',
        genre: 'Simulation',
        releaseYear: 2015,
        description: 'Manage a farm, grow crops, and raise animals in this relaxing simulation game.',
        platform: ['PC', 'Mobile'],
        popularity: 65,
    },
    {
        gameId: 'G005',
        userId: 'user567',
        title: 'Battle Arena',
        genre: 'Action',
        releaseYear: 2014,
        description: 'Fight in a variety of arenas and prove your skills in intense battles.',
        platform: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
        popularity: 80,
    },
    {
        gameId: 'G006',
        userId: 'user678',
        title: 'Zombie Survival',
        genre: 'Horror',
        releaseYear: 2021,
        description: 'Survive against waves of zombies in a post-apocalyptic world.',
        platform: ['PC', 'Xbox'],
        popularity: 78,
    },
    {
        gameId: 'G007',
        userId: 'user789',
        title: 'Magic Realms',
        genre: 'Fantasy',
        releaseYear: 2022,
        description: 'Journey through magical realms, mastering spells and defeating mythical creatures.',
        platform: ['PlayStation', 'Nintendo Switch'],
        popularity: 85,
    },
    {
        gameId: 'G008',
        userId: 'user890',
        title: 'World Builder',
        genre: 'Strategy',
        releaseYear: 2020,
        description: 'Build and expand your own world, manage resources, and strategize against enemies.',
        platform: ['PC'],
        popularity: 72,
    },
    {
        gameId: 'G009',
        userId: 'user900',
        title: 'Racing Legends',
        genre: 'Racing',
        releaseYear: 2011,
        description: 'Race through diverse tracks, customizing cars and competing against top drivers.',
        platform: ['PC', 'Xbox', 'PlayStation'],
        popularity: 88,
    },
    {
        gameId: 'G010',
        userId: 'user000',
        title: 'Space Colonization',
        genre: 'Sci-Fi',
        releaseYear: 2003,
        description: 'Establish and manage a human colony on a distant planet, overcoming various challenges.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 90,
    },
    {
        gameId: 'G011',
        userId: 'user123',
        title: 'Medieval Kingdoms',
        genre: 'Strategy',
        releaseYear: 2008,
        description: 'Command armies and build your kingdom in a historical medieval setting.',
        platform: ['PC', 'Mobile'],
        popularity: 70,
    },
    {
        gameId: 'G012',
        userId: 'user456',
        title: 'Alien Invasion',
        genre: 'Sci-Fi',
        releaseYear: 2012,
        description: 'Defend Earth from alien invaders in this fast-paced action shooter.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 82,
    },
    {
        gameId: 'G013',
        userId: 'user789',
        title: 'Fantasy Quest',
        genre: 'Fantasy',
        releaseYear: 2001,
        description: 'Explore a mythical world filled with magical creatures and ancient treasures.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 78,
    },
    {
        gameId: 'G014',
        userId: 'user345',
        title: 'Cyber Runner',
        genre: 'Action',
        releaseYear: 2013,
        description: 'Run through cyberpunk cities, dodging obstacles and fighting enemies.',
        platform: ['Mobile', 'Nintendo Switch'],
        popularity: 83,
    },
    {
        gameId: 'G015',
        userId: 'user890',
        title: 'Heros Journey',
        genre: 'Adventure',
        releaseYear: 2000,
        description: 'A classic tale of heroism and discovery in a world of magic and mystery.',
        platform: ['PC', 'PlayStation'],
        popularity: 77,
    },
    {
        gameId: 'G016',
        userId: 'user567',
        title: 'Galactic Conquest',
        genre: 'Strategy',
        releaseYear: 2009,
        description: 'Expand your empire across the galaxy in this strategic space simulation.',
        platform: ['PC', 'Xbox'],
        popularity: 85,
    },
    {
        gameId: 'G017',
        userId: 'user012',
        title: 'Adventure Quest',
        genre: 'RPG',
        releaseYear: 2002,
        description: 'Embark on an epic adventure to save the kingdom from the ancient curse.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 87,
    },
    {
        gameId: 'G018',
        userId: 'user123',
        title: 'Mystery of the Syberia',
        genre: 'Puzzle',
        releaseYear: 2021,
        description: 'Solve freezing puzzles to escape from the harsh constraints.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 75,
    },
    {
        gameId: 'G019',
        userId: 'user456',
        title: 'Space and Mind Problem',
        genre: 'Sci-Fi',
        releaseYear: 2013,
        description: 'Rethink the vast universe and consciousness to solve hardest problem.',
        platform: ['PC', 'PlayStation'],
        popularity: 92,
    },
    {
        gameId: 'G020',
        userId: 'user789',
        title: 'Predator',
        genre: 'RPG',
        releaseYear: 2010,
        description: 'Manage a farm, grow crops, and raise animals in this relaxing simulation game.',
        platform: ['PC', 'Mobile'],
        popularity: 65,
    },
    {
        gameId: 'G021',
        userId: 'user678',
        title: 'Dragon’s Lair',
        genre: 'Adventure',
        releaseYear: 2020,
        description: 'Explore dangerous dungeons filled with dragons and hidden treasures.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 81,
    },
    {
        gameId: 'G022',
        userId: 'user234',
        title: 'Island Escape',
        genre: 'Survival',
        releaseYear: 2019,
        description: 'Survive on a deserted island by crafting tools and gathering resources.',
        platform: ['Mobile', 'Nintendo Switch'],
        popularity: 74,
    },
    {
        gameId: 'G023',
        userId: 'user345',
        title: 'Virtual Pet World',
        genre: 'Simulation',
        releaseYear: 2021,
        description: 'Take care of virtual pets in an interactive and vibrant online world.',
        platform: ['PC', 'Mobile'],
        popularity: 68,
    },
    {
        gameId: 'G024',
        userId: 'user890',
        title: 'Galactic Warzone',
        genre: 'Sci-Fi',
        releaseYear: 2023,
        description: 'Command fleets and battle alien forces in this intense space warfare game.',
        platform: ['PC', 'PlayStation'],
        popularity: 91,
    },
    {
        gameId: 'G025',
        userId: 'user123',
        title: 'Street Racer 5',
        genre: 'Racing',
        releaseYear: 2020,
        description: 'Experience high-speed racing through city streets with customizable cars.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 79,
    },
    {
        gameId: 'G026',
        userId: 'user678',
        title: 'Mystic Mountains',
        genre: 'Fantasy',
        releaseYear: 2021,
        description: 'Climb the mystical mountains and uncover ancient secrets.',
        platform: ['Nintendo Switch', 'Mobile'],
        popularity: 83,
    },
    {
        gameId: 'G027',
        userId: 'user456',
        title: 'Football Dynasty',
        genre: 'Sports',
        releaseYear: 2018,
        description: 'Lead your team to victory in this strategic football management game.',
        platform: ['PC', 'PlayStation'],
        popularity: 72,
    },
    {
        gameId: 'G028',
        userId: 'user345',
        title: 'Underwater Quest',
        genre: 'Adventure',
        releaseYear: 2022,
        description: 'Dive deep and discover underwater cities filled with challenges and treasures.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 88,
    },
    {
        gameId: 'G029',
        userId: 'user234',
        title: 'Haunted Mansion',
        genre: 'Horror',
        releaseYear: 2021,
        description: 'Navigate a haunted mansion, solving puzzles and avoiding ghosts.',
        platform: ['PlayStation', 'Xbox'],
        popularity: 77,
    },
    {
        gameId: 'G030',
        userId: 'user567',
        title: 'World of Warriors',
        genre: 'Action',
        releaseYear: 2019,
        description: 'Battle through historical eras with famous warriors from across time.',
        platform: ['PC', 'PlayStation'],
        popularity: 85,
    },
    {
        gameId: 'G031',
        userId: 'user789',
        title: 'Island Kingdom',
        genre: 'Strategy',
        releaseYear: 2022,
        description: 'Build and defend your island kingdom against pirates and invaders.',
        platform: ['PC', 'Mobile'],
        popularity: 70,
    },
    {
        gameId: 'G032',
        userId: 'user678',
        title: 'Future City',
        genre: 'Simulation',
        releaseYear: 2020,
        description: 'Construct a futuristic city with advanced technology and AI citizens.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 74,
    },
    {
        gameId: 'G033',
        userId: 'user890',
        title: 'Hero’s Saga',
        genre: 'RPG',
        releaseYear: 2023,
        description: 'Embark on an epic journey across kingdoms to defeat a rising evil.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 93,
    },
    {
        gameId: 'G034',
        userId: 'user012',
        title: 'Puzzle Kingdom',
        genre: 'Puzzle',
        releaseYear: 2018,
        description: 'Solve intricate puzzles to advance through kingdoms and unlock rewards.',
        platform: ['PC', 'Mobile'],
        popularity: 69,
    },
    {
        gameId: 'G035',
        userId: 'user234',
        title: 'Alien Quest',
        genre: 'Sci-Fi',
        releaseYear: 2022,
        description: 'A space adventure where you explore unknown planets and battle aliens.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 84,
    },
    {
        gameId: 'G036',
        userId: 'user345',
        title: 'Castle Siege',
        genre: 'Strategy',
        releaseYear: 2021,
        description: 'Defend your castle and lead your army in strategic battles.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 80,
    },
    {
        gameId: 'G037',
        userId: 'user456',
        title: 'Hidden Depths',
        genre: 'Adventure',
        releaseYear: 2020,
        description: 'Explore mysterious caves and underwater cities filled with treasures.',
        platform: ['PC', 'Xbox'],
        popularity: 75,
    },
    {
        gameId: 'G038',
        userId: 'user567',
        title: 'Lost in Time',
        genre: 'Sci-Fi',
        releaseYear: 2021,
        description: 'Travel through time and prevent a catastrophic event from occurring.',
        platform: ['PC', 'PlayStation'],
        popularity: 86,
    },
    {
        gameId: 'G039',
        userId: 'user789',
        title: 'Monster Battleground',
        genre: 'Action',
        releaseYear: 2023,
        description: 'Fight powerful monsters in various exotic locations to become the ultimate champion.',
        platform: ['PC', 'Xbox', 'Nintendo Switch'],
        popularity: 59,
    },
    {
        gameId: 'G040',
        userId: 'user890',
        title: 'Cyber Warfare',
        genre: 'Strategy',
        releaseYear: 2019,
        description: 'Engage in cyber battles and defend against virtual attacks in this digital world.',
        platform: ['PC', 'Mobile'],
        popularity: 68,
    },
]