import { Game, UserProfile } from "../shared/types";

export const games: Game[] = [
    {
        gameId: 'G001',
        userId: 'user123',
        title: 'Adventure Quest',
        genre: 'RPG',
        releaseYear: 2022,
        description: 'Embark on an epic adventure to save the kingdom from the ancient curse.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 87,
    },
    {
        gameId: 'G002',
        userId: 'user123',
        title: 'Mystery of the Ancients',
        genre: 'Puzzle',
        releaseYear: 2021,
        description: 'Solve ancient puzzles to uncover the secrets of a long-lost civilization.',
        platform: ['PC', 'Nintendo Switch'],
        popularity: 75,
    },
    {
        gameId: 'G003',
        userId: 'user234',
        title: 'Space Odyssey',
        genre: 'Sci-Fi',
        releaseYear: 2003,
        description: 'Explore the vast universe and battle alien species to protect humanity.',
        platform: ['PC', 'PlayStation'],
        popularity: 92,
    },
    {
        gameId: 'G004',
        userId: 'user234',
        title: 'Farm Frenzy',
        genre: 'Simulation',
        releaseYear: 2015,
        description: 'Manage a farm, grow crops, and raise animals in this relaxing simulation game.',
        platform: ['PC', 'Mobile'],
        popularity: 65,
    },
    {
        gameId: 'G005',
        userId: 'user567',
        title: 'Battle Arena',
        genre: 'Action',
        releaseYear: 2014,
        description: 'Fight in a variety of arenas and prove your skills in intense battles.',
        platform: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
        popularity: 80,
    },
    {
        gameId: 'G006',
        userId: 'user567',
        title: 'Zombie Survival',
        genre: 'Horror',
        releaseYear: 2021,
        description: 'Survive against waves of zombies in a post-apocalyptic world.',
        platform: ['PC', 'Xbox'],
        popularity: 78,
    },
    {
        gameId: 'G007',
        userId: 'user123',
        title: 'Magic Realms',
        genre: 'Fantasy',
        releaseYear: 2022,
        description: 'Journey through magical realms, mastering spells and defeating mythical creatures.',
        platform: ['PlayStation', 'Nintendo Switch'],
        popularity: 85,
    },
    {
        gameId: 'G008',
        userId: 'user567',
        title: 'Galactic Conquest',
        genre: 'Strategy',
        releaseYear: 2009,
        description: 'Expand your empire across the galaxy in this strategic space simulation.',
        platform: ['PC', 'Xbox'],
        popularity: 85,
    },
    {
        gameId: 'G009',
        userId: 'user234',
        title: 'Alien Invasion',
        genre: 'Sci-Fi',
        releaseYear: 2012,
        description: 'Defend Earth from alien invaders in this fast-paced action shooter.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 82,
    },
    {
        gameId: 'G010',
        userId: 'user567',
        title: 'Cyber Runner',
        genre: 'Action',
        releaseYear: 2013,
        description: 'Run through cyberpunk cities, dodging obstacles and fighting enemies.',
        platform: ['Mobile', 'Nintendo Switch'],
        popularity: 83,
    },
    {
        gameId: 'G011',
        userId: 'user123',
        title: 'Medieval Kingdoms',
        genre: 'Strategy',
        releaseYear: 2008,
        description: 'Command armies and build your kingdom in a historical medieval setting.',
        platform: ['PC', 'Mobile'],
        popularity: 70,
    },
    {
        gameId: 'G012',
        userId: 'user567',
        title: 'Space Colonization',
        genre: 'Sci-Fi',
        releaseYear: 2003,
        description: 'Establish and manage a human colony on a distant planet, overcoming various challenges.',
        platform: ['PC', 'PlayStation', 'Xbox'],
        popularity: 90,
    }
];


export const users: UserProfile[] = [
    {
        userId: 'user123',
        username: 'alicejohnson21',
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        joinedDate: '2021-01-15',
        favoriteGenres: ['RPG', 'Adventure'],
    },
    {
        userId: 'user234',
        username: 'bobsmith87',
        name: 'Bob Smith',
        email: 'bob.smith@example.com',
        joinedDate: '2021-03-22',
        favoriteGenres: ['Puzzle', 'Survival'],
    },
    {
        userId: 'user567',
        username: 'ethanhunt007',
        name: 'Ethan Hunt',
        email: 'ethan.hunt@example.com',
        joinedDate: '2021-07-18',
        favoriteGenres: ['Action', 'Adventure'],
    }
];
